#!/bin/bash

PROJECT=$1
VAR_NAME=$2
NEW_VAL=$3

RESULT1=$(curl -X DELETE https://circleci.com/api/v1.1/project/github/$CIRCLE_USERNAME/$PROJECT/envvar/$VAR_NAME?circle-token=$CIRCLE_API_TOKEN)

if [[ $RESULT1 == *"ok"* ]]; then 
	RESULT2=$(curl -X POST --header "Content-Type: application/json" -d '{"name":"'$VAR_NAME'", "value":"'$NEW_VAL'"}' https://circleci.com/api/v1.1/project/github/$CIRCLE_USERNAME/$PROJECT/envvar?circle-token=$CIRCLE_API_TOKEN)
else
	echo -e "\033[31mError: variable not found!\033[0m"
fi

if [[ $RESULT2 == *$VAR_NAME* ]]; then 
	echo -e  "\033[32mSuccess!\033[0m"
else
	echo -e  "\e[31mError updating variable\e[0m"
fi
	
